# Module manifest for module PSMetrolink
# Generated by: Phil Carney

@{
    RootModule        = "PSMetrolink.psm1"
    ModuleVersion     = "1.0.0.0"
    GUID              = "12ebb870-7f33-4a23-b371-87dd4cad8125"
    Author            = "Phil Carney"
    CompanyName       = "N/A"
    Copyright         = "(c) Phil Carney. All rights reserved."
    Description       = "Find out how late your Met will be with Powershell."
    # CompatiblePSEditions = @()
    # PowerShellVersion = ""
    # PowerShellHostName = ""
    # PowerShellHostVersion = ""
    # DotNetFrameworkVersion = ""
    # CLRVersion = ""
    # ProcessorArchitecture = ""
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    FunctionsToExport = @("Get-Metrolink")
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @("Get-Met", "Get-Tram")
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{
        PSData = @{
            Tags       = @("metrolink", "met", "tram", "public-transport", "rest", "rest-api")
            ProjectUri = "https://github.com/philccarney/psmetrolink"
            # LicenseUri = ""
            # IconUri = ""
            # ReleaseNotes = ""
        } # End of PSData hashtable
    } # End of PrivateData hashtable
    # HelpInfo URI of this module
    # HelpInfoURI = ""
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ""
}